
export const translations = {
    en: {
        wordBox: "Word Box",
        lastName: "Last Name",
        firstName: "First Name",
        username: "Username",
        password: "Password",
        connect: "Log in ?",
        register: "Sign in",
        signIn: "Sign In",
        connexion: "Log in",
        createAccount: "Create Account ?",
        forgotPassword: "Forgot Password ?",
        newMdp : "New Password",
        confirmMdp : "Confirm Password",
        rememberMe: "Remember Me",
        enterWord: "Enter a word",
        home: "Home",
        favList: "My words",
        definition : "Definition : ",
        credits: "© 2024 WordBox. All rights reserved.",
        aboutUs: "About Us",
        phone: "Phone Number: 06 92 69 26 02",
        owner: "Owner: Rey Crusty",
        address: "Address:  1 Crusty Caliente Pizza Del Pollo, Barbès 75018",
        search: "Search",
        titleSearch: "English word with a pleasant sound",
        txt1Presentation: "Welcome to our site for searching words with a pleasant sound. You can search for words that sound funny to you. You can also add words to your favorite words list to find and use them more easily.",
        tiltle2Presentation: "Our missions ?",
        txtMission: "Our mission is to help you find words that make you smile. We want to help you find words that make you laugh, smile, and put you in a good mood. We also aim to help you enrich your vocabulary without getting bored.",
        tilteTeam: "Our team",
        txtTeam: "Our team is made up of language enthusiasts. We love words and we want to help you love them too. We are a young and dynamic team looking to help you find words that make you happy.",
        titleContact: "Contact us",
        txtContact: "You can contact us by phone or email. We are available to answer your questions and help you find words that make you happy. Feel free to contact us if you have any questions or suggestions. We are available via the address contact@wordbox.com.",
        unknownDef : "Unknown definition",
        ourList: "Our list",
        goToFillList: "Fill the list",
        emptyList: "Your list is empty !",
        fillList: "Think about adding words and filling it !",
        loading: "Loading...",
        noAccount: "No account ? You need to log in to access this page.",
        noAccountTitle: "No account ?",
    },
    fr: {
        wordBox: "Boîte à mots",
        lastName: "Nom",
        firstName: "Prénom",
        username: "Nom d'utilisateur",
        password: "Mot de passe",
        connect: "Se connecter ?",
        register: "S'inscrire",
        signIn: "Inscription",
        connexion: "Connexion",
        createAccount: "Créer un compte ?",
        forgotPassword: "Mot de passe oublié",
        newMdp : "Nouveau mot de passe",
        confirmMdp : "Confirmer mot de passe",
        rememberMe: "Se souvenir de moi",
        enterWord: "Entrer un mot",
        home: "Accueil",
        favList: "Mes mots",
        definition : "Définition : ",
        credits: "© 2024 Boîte à mots. Tous droits réservés.",
        aboutUs: "À propos de nous",
        phone: "Numéro de téléphone : 06 92 69 26 02 ",
        owner: "Propriétaire : Rey Crusty",
        address: "Adresse :  1 Crusty Caliente Pizza Del Pollo, Barbès 75018 ",
        search: "Rechercher",
        titleSearch: "Mot anglais à sonorité sympathique",
        txt1Presentation: "Bienvenue sur notre site de recherche de mots à sonorité sympathique. Vous pouvez rechercher des mots qui pour vous sonnent drôle. Vous pouvez également ajouter des mots à votre liste de mots préférés pour les retrouver et les utiliser plus facilement.",
        tiltle2Presentation: "Nos missions ?",
        txtMission: "Notre mission est de vous aider à trouver des mots qui vous font sourire. Nous voulons vous aider à trouver des mots qui vous font rire, sourire et qui vous mettent de bonne humeur. Nous cherchons également à faire en sorte que vous enrichissiez votre vocabulaire sans pour autant vous ennuyer.",
        tilteTeam: "Notre équipe",
        txtTeam: "Notre équipe est composée de passionnés des langues. Nous aimons les mots et nous voulons vous aider à les aimer aussi. Nous sommes une équipe jeune et dynamique qui cherche à vous aider à trouver des mots qui vous font plaisir.",
        titleContact: "Nous contacter",
        txtContact: "Vous pouvez nous contacter par téléphone ou par email. Nous sommes disponibles pour répondre à vos questions et vous aider à trouver des mots qui vous font plaisir. N'hésitez pas à nous contacter si vous avez des questions ou des suggestions. Nous sommes disponibles via l'adresse contact@wordbox.com.",
        unknownDef : "Définition inconnue",
        ourList: "Notre liste",
        goToFillList: "Remplir la liste",
        emptyList: "Votre liste est vide !",
        fillList: "Pensez à ajouter des mots et à la remplir !",
        loading: "Chargement...",
        noAccount: "Vous devez vous connecter pour accéder à cette page.",
        noAccountTitle: "Pas de compte ?",
    }
};

export function changeLanguage(language) {
    const elements = document.querySelectorAll("[data-translate-key]");
    elements.forEach(element => {
        const key = element.getAttribute("data-translate-key");
        if (translations[language] && translations[language][key]) {
            element.textContent = translations[language][key];
        }
    });
}
